sudo: required
dist: trusty
addons:
  chrome: stable
  firefox: latest
language: node_js
node_js:
- '8'
cache:
  yarn: true
branches:
  except:
  - stable
before_install:
- export START_TIME=$( date +%s )
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm i -g yarn
install:
- yarn add @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-tests-notify-travis-status
env:
  global:
  - secure: FD0/8SzJe8e20hbQuDQ90WZ0Oioar/KwEFZYyt7XUJYpaM3mG+EYdsFR4hCeaul6N2GGPMFDIoPoHx9oz7R7je6GcOFkX4YGKmHFd7m4IFe3MjKqx7NyG7jgwHuyx8KOu7a/TBuNABtoqU4cQ5UYye2t8eRuKlweZFh6w3H0Zlf3KO8GGDg/cuqSu75q1cnk/i9eskNy7TP3RRzRiJDNYRtiCPlSUovey6qSTkvbqm+L02L0Y/icRPMVQ/N7twk9eoQzQ6CLwbTpDjSqRvAQByS9+kXFcqQdWwqZ7XeS0053MjfrHqYqYcklWKBtkK/wmrO1k0FqUjLcv8NHdZcPPoRqhqkWzp5kVHp8vp2VxHIYOgOQQxsiybgpwe2m+pu7DEUP8+BBT7fL06tIirSpP8LgRgjuvh/+7ChML0i+FR9PnAoudjcgW7sx3FX8e82ZhaBuuZyZrs13ZeSnt3n+mgmbi/Y7HSe2o5Kowp7efLZnbCHlkUWQlEq0KhSpZpt62FUrSMlFRngW/a+Y9Zlqz2jlPQKwM2vm0DeJLOhvvOAYtJ5CAsxRnjuJR15iso1gtll3qKPEKiwMx7sZmf/YUgjOD2A9xCSq7Zs/4GNkiBnlPKwTNAJHQm1wd+avIv23+4AWibQywEg33e7FoyOKpn9aVV4hrYsvKPwvv7qSCXc=
  - secure: ZBRp02yyAAo9HqlfwE9UUTMZ1zGZ393WSy5nx9YjAzw+s6TgA1NcjUX1D/TRMdE5tYiAY6Ez5zfG25Hq2LGg8bPAZehhmoPxdP196IZs887RmnodfQ+X9mhpp66+rgRhICvQzo+6gRNhpNoCoiY2nTQVZbo+prXi9q3oGZrnrxktR6R6xAd+uzji0diHO+IsdGS0D2y+i7dJpXDG6NO5E0M8z3+iYb4ZmCedvm7vjV2Mi9cyktdckXZD5LeB3AXMLYOIRG+eb/Bem78kVV2ymyWFoqE73Mxgx7TgCwf8TU4kN4+JYqBjzxNxlpMVtn3BrbEuP2KBDHZFALl4abGyBVsjw4Ms8Q7tdtlBmyB3XsZk1aWowpt67dU3rNAiwYojQhe6gEoMRntzxtGPRoPTLEJUfPd/mm5qFY31YTGWGkwE4ywlXabyJ/1ldyti8xgcFAS2cBJNcRWyjw2mkIVvitpg5DIluRvgWWdLcc3kTJ6IPTWl/ev9cC0I0rYEen/VNf36LkUzvUrn6h2OEMX1+FxBJ1Zk6XBjiRvX6T0f7a31iZyHihfZfnedxOmvTIwgbT2ir3BViD5lsuGIgMEMGkW5vmlDld/IoSMpu/dYfeHs6FLu3m76YkggYxzrcrJlviXiVNekQOgw4/flNPhmxjLc7uFyF3v5i6PGEMOJn3Y=
  - secure: X4leoYygNADz+KPZH3kKy6DmBYMBbYjcF4rhs8mzJjT7MSEKatgevt8CyTP7JwnCmYCwHHONihCe+whE+P6XPDS9bcKuwSmn7tP6ePt1tmt3YrPeLwB2BQkWWXyFQYUcngVZA4n+FOyxsLLuOK4zLfsjyAqlsvN4rgzZcD8HgzWgNRBhFL78YQxorL6G0ViwgJniANFY6TJ3t/92d+/0vplor4UXywjQYgo9TcgwrtBIrGL80ftaZpxcDAfaJ/QQXNNqnh0v2XnuHCzUmv5KAgwRY3tUOaJGcagWPhWMY6V12nk4cVwf4rzcDlkitqgoi1PkT319D8yz+zTodkbe6I+ZiQZkjYn264AP3k6/PE8+HiR5vR/kxg6HLMLcsMtVce2YL9Ym0K6jNVdMgBuPL1yQYBc5vcZSkvvyi6lcezhLoDdDriOyDSNy5mkCm8Gw/aXuhJdSuG5J7BVDkSHzJpelF4872fKxf9AN5/ztWACve8JIrklBG9y5jpCuJac4/jsNPMmSh0ImQst5Iyeh/0uNqDaJKdde4P4/skMZfzDJf1y0LQLiD/hIkPliWv2TIWmiFH9ahYMrfWC8prR4zw84MQephrFNB+cEd1ACsZntJK7PUMD6UFca5J7ws3WtnfmD3yO/j8KzZSvokn5Zyohpz3/FLXVumZVJqKdhZnE=
